version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
            
    environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    volumes:
        - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #    - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
        - rabbitmq-net
networks:
  rabbitmq-net:
    driver: bridge
